config/routes.rb
Rails.application.routes.draw do
  resources :taks
  root 'taks#index'

end

app/models/tak.rb
class Tak < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/taks_controller.rb
class TaksController < ApplicationController
  before_action :set_tak, only: [:show, :edit, :update, :destroy]
  # GET /taks
  # GET /taks.json
  def index
    @taks = Tak.all
    @incomplete_tasks = Tak.where(complete: false)
    @complete_tasks = Tak.where(complete: true)
  
  end

  # GET /taks/1
  # GET /taks/1.json
  def show
  end

  # GET /taks/new
  def new
   @tak = Tak.new
   @incomplete_tasks = Tak.where(complete: false)
    @complete_tasks = Tak.where(complete: true)
  end

  # GET /taks/1/edit
  def edit
  end

  # POST /taks
  # POST /taks.json
  def create
    @tak = Tak.new(tak_params)

    respond_to do |format|
      if @tak.save
        #format.html { redirect_to @tak, notice: 'Tak was successfully created.' }
        #format.json { render :show, status: :created, location: @tak }
        format.js
      else
        format.html { render :new }
        format.json { render json: @tak.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taks/1
  # PATCH/PUT /taks/1.json
  def update
    respond_to do |format|
      if @tak.update(tak_params)
        #format.html { redirect_to @tak, notice: 'Tak was successfully updated.' }
       # format.json { render :show, status: :ok, location: @tak }
       format.js
      else
        format.html { render :edit }
        format.json { render json: @tak.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taks/1
  # DELETE /taks/1.json
  def destroy
    @tak.destroy
    respond_to do |format|
      #format.html { redirect_to taks_url, notice: 'Tak was successfully destroyed.' }
      #format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tak
      @tak = Tak.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tak_params
      params.require(:tak).permit(:name, :complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/taks_helper.rb
module TaksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

</head>
<body>

<div class="panel panel-default">
	<div class="panel-heading">
		<h2>Make your own todo Lists</h2>
	</div>
	<div class="panel-body">
	<%= yield %>
</div>
</div>
<footer class="footer">
  <div class="container" style="padding-bottom:2%;">
    <span class="text-muted pull-left">
    	Created by Gowtham GGS
    </span>
    <span class="pull-right">
    	<a href="https://github.com/ggsgowtham/todolist" target="_blank">Github</a>
    </span>
  </div>
</footer>


</body>
</html>

app/views/taks/_form.html.erb
<%= form_for(@tak, :remote=> true) do |f| %> 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="action">
    <%= f.submit  class: "btn btn-default" %>
  </div>
<% end %>

app/views/taks/_tak.html.erb
<ul class="list-group">
<%= form_for tak, remote: true do |f| %>
  	<% if tak.complete %>
  		<%= hidden_field_tag "completed_tasks[]", tak.id %>
  	<% end %>
  <li class="list-group-item">
  	<%= f.check_box :complete %>
  	<span class="taskName <%= 'strikeThrough' if tak.complete %>">
  		<%= label :complete, tak.name %>
  	</span>
  	<span  class="pull-right">
  	<%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe ,tak, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
  </span>
</li>
<% end %>
</ul>

app/views/taks/create.js.erb
$('#new_tak').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@tak) %>');

$('#edit_tak_<%= @tak.id %>').submitOnCheck();
var incmpUlCnt = $("#incomplete_tasks ul").length	
$("#itemsLeftCount").text(incmpUlCnt);

app/views/taks/destroy.js.erb
$('#edit_tak_<%= @tak.id %>').remove();
var incmpUlCnt = $("#incomplete_tasks ul").length	

$("#itemsLeftCount").text(--incmpUlCnt);

app/views/taks/edit.html.erb
<h1>Editing Tak</h1>

<%= render 'form' %>

<%= link_to 'Show', @tak %> |
<%= link_to 'Back', taks_path %>

app/views/taks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
	<div class="panel-body" >
		<div class="pull-left">
		<%= link_to 'Create Task', new_tak_path, id: "new_link", remote: true,class: "btn btn-primary"   %>
		</div>
		<div class="pull-right">
		<% if(@incomplete_tasks.length > 0) %>	
			<label class="text-muted">Active Items: </label>	
			<span class="badge" id="itemsLeftCount">
				<%= @incomplete_tasks.length %>
			</span>	
		<% end %>	
		<%= link_to 'All', "javasciprt:;", id: "all_tasks", remote: true, class: "btn btn-default"%>
		<%= link_to 'Active', "javasciprt:;", id: "active_tasks", remote: true, class: "btn btn-success"%>
		<%= link_to 'Completed', "javasciprt:;", id: "completed_tasks", remote: true, class: "btn btn-danger"%>
		</div>
	</div>
</div>	

<div class="panel panel-success" id="incomplete_panel">
	<div class="panel-heading">
		<h3>Active Tasks</h3>	
	</div>
	<div class="panel-body tasks" id="incomplete_tasks">
		<% if(@incomplete_tasks.length > 0) %>	
			<%= render @incomplete_tasks %>
		<% else %>
			<p class="text-muted">Currently no active tasks! craete one</p>
		<% end %>
	</div>
</div>

<div class="panel panel-danger" id="complete_panel">
	<div class="panel-heading">
		<h3>Completed Tasks</h3>	
	</div>
	<div class="panel-body tasks" id="complete_tasks">
		<% if(@complete_tasks.length > 0) %>	
		<%= render @complete_tasks %>
		<% else %>
			<p class="text-muted">Currently no completed tasks left! </p>
		<% end %>
	</div>
</div>

app/views/taks/new.html.erb
<h1>New Tak</h1>

<%= render 'form' %>

<%= link_to 'Back', taks_path %>

app/views/taks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/taks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tak.name %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @tak.complete %>
</p>

<%= link_to 'Edit', edit_tak_path(@tak) %> |
<%= link_to 'Back', taks_path %>

app/views/taks/update.js.erb
//for removing the text box on the fly and creating label

var spanInput = $('#edit_tak_<%= @tak.id %>').find('span .editForm'),
	textValue = spanInput.val(),
	html = '<label for="complete_<%= @tak.id %>">'+ textValue +'</label>';
if(textValue && textValue.length > 0){
	$('#edit_tak_<%= @tak.id %>').find('span.taskName').html(html);
}
var incmpUlCnt = $("#incomplete_tasks ul").length	

<% if @tak.complete? %> 
	--incmpUlCnt;
<% else %>
	++incmpUlCnt;
<% end %>

<% if @tak.complete? %>
  $('#edit_tak_<%= @tak.id %>').appendTo('#complete_tasks').find("span.taskName").addClass('strikeThrough');
<% else %>
  $('#edit_tak_<%= @tak.id %>').appendTo('#incomplete_tasks').find("span.strikeThrough").removeClass("strikeThrough");
<% end %>

$("#itemsLeftCount").text(incmpUlCnt);
 	